ref: ultramarine/39/base/${basearch}
releasever: "39"

include:
  - ../common/common.yaml
  - ../common/hardware.yaml
  - common/release.yaml
  - common/common.yaml

repos:
  - ultramarine
  - terra
  - rpmfusion-free
  - rpmfusion-nonfree
  - rpmfusion-free-updates
  - rpmfusion-nonfree-updates
  - fedora
  - fedora-updates
  # - fedora-updates-testing # TODO: Remove once Fedora 39 hits stable
  - openh264

packages:
  - ultramarine-release-identity-basic
  - ultramarine-release-basic
