ref: ultramarine/39/base/${basearch}
releasever: "39"

include:
  - ../common/common.yaml
  - common/release.yaml

repos:
  - ultramarine
  - terra
  - rpmfusion-free
  - rpmfusion-nonfree
  - rpmfusion-free-updates
  - rpmfusion-nonfree-updates
  - fedora
  - fedora-updates

packages:
  - ultramarine-release-basic
  - ultramarine-release-identity-basic
