ref: ultramarine/38/base/${basearch}
releasever: "38"

include:
  - common/common.yaml

repos:
  - ultramarine
  - terra
  - rpmfusion-free
  - rpmfusion-nonfree
  - rpmfusion-free-updates
  - rpmfusion-nonfree-updates
  - fedora
  - fedora-updates
