name: CI - ISOs

on:
  workflow_dispatch:
  schedule:
    # every week at midnight
    - cron: "0 0 * * *"

jobs:
  ci:
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.build.product }}-${{ matrix.build.variant }}
      cancel-in-progress: false
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        build:
          - product: ultramarine
            variant: base
          - product: ultramarine
            variant: flagship
          - product: ultramarine
            variant: gnome
          - product: ultramarine
            variant: pantheon
          - product: ultramarine
            variant: kde
          - product: tau
            variant: home
    uses: ./.github/workflows/iso.yml
    with:
      product: ${{ matrix.build.product }}
      variant: ${{ matrix.build.variant }}
    secrets: inherit
