name: CI - OSTree

on:
  push:
    paths-ignore:
      - "README.md"
  workflow_dispatch:
  schedule:
    # every week at midnight
    - cron: "0 0 * * *"

jobs:
  ci:
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.variant }}
      cancel-in-progress: false
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        variant:
          - ultramarine/base
          - ultramarine/flagship
          - ultramarine/gnome
          - ultramarine/pantheon
          - ultramarine/kde
          - tau/home
    uses: ./.github/workflows/ostree.yml
    with:
      variant: ${{ matrix.variant }}
    secrets: inherit
