name: Build and deploy OSTree image

on:
  push:
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ARM64
    runs-on: ${{ matrix.os }}
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --cap-add=SYS_ADMIN --privileged
      volumes:
        - ostree_cache:/var/cache/compose
        - ostree_repo:/var/ostree

    steps:
      - name: Install dependencies
        id: deps
        run: |
          dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/terrapkg/subatomic-repos/raw/main/um37.repo
          sudo dnf install -y rpm-ostree melody ostree just --enablerepo=updates-testing


      - name: Checkout
        uses: actions/checkout@v3

      - name: OSTree Cache
        uses: actions/cache@v3
        with:
          path: |
            cache/
          key: ${{ runner.os }}-${{ matrix.os }}-ostree


      - name: Build OSTree
        id: build
        run: just ostree_cache=/var/cache/compose ostree_repo=/var/ostree build


      - name: Export OSTree commit
        id: export
        run: ostree export --repo /var/ostree ultramarine/37/x86_64/lapis > output.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ostree
          path: output.tar

  deploy:
    runs-on: ubuntu-latest
    # need artifacts from build job
    needs: build
    container:
      image: ghcr.io/terrapkg/builder:main


    # use matrix for each arch
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ostree

      - name: Upload OSTree commit to subatomic
        run: |
          subatomic-cli upload \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            ostree --branch ultramarine/37/x86_64/lapis output.tar || true

