name: Build and deploy OSTree image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ARM64
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/terrapkg/builder:main
      options: --cap-add=SYS_ADMIN --privileged
      volumes:
        - ostree_cache:/var/cache/compose
        - ostree_repo:/var/ostree

    steps:
      - name: DNF Cache
        uses: actions/cache@v3
        with:
          path: /var/cache/dnf
          key: ostree
      - name: Install dependencies
        id: deps
        run: |
          sudo dnf install -y rpm-ostree melody just python3-pip pkg-config wget ostree ostree-devel rpm-ostree git hfsplus-tools flatpak dbus dbus-daemon rpmdevtools make mock selinux-policy python3-pip jq @development-tools gcc cairo-devel python3-devel 'pkgconfig(gobject-introspection-1.0)' 'pkgconfig(cairo-gobject)' 'dnf-command(config-manager)'

      - name: Install python dependencies
        id: deps-py
        run: pip install ostree-push yq

      - name: Checkout
        uses: actions/checkout@v3

      - name: OSTree Cache
        uses: actions/cache@v3
        with:
          path: /var/cache/compose
          key: ostree

      - name: Build OSTree
        id: build
        run: just ostree_cache=/var/cache/compose ostree_repo=/var/ostree build

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
          echo "${{ secrets.GPG_KEY }}" | gpg --import

      - name: Sign OSTree commit
        run: |
          ostree --repo=/var/ostree gpg-sign ultramarine/37/x86_64/lapis ${{ secrets.GPG_ID }} -v
          ostree --repo=/var/ostree summary -u

      - name: Import SSH credentials
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.REPO_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REPO_KNOWN_HOSTS }}

      - name: Push OSTree commit
        run: ostree-push --repo=/var/ostree repo@${{ secrets.REPO_IP }}:/var/www/repo.fyralabs.com/ostree
