name: Build and deploy OSTree image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - ARM64
    runs-on: ${{ matrix.os }}
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --cap-add=SYS_ADMIN --privileged
      volumes:
        - ostree_cache:/var/cache/compose
        - ostree_repo:/var/ostree

    steps:
      - name: Install dependencies
        id: deps
        run: |
          dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/terrapkg/subatomic-repos/raw/main/um37.repo
          sudo dnf install -y rpm-ostree melody ostree just python3-pip pkg-config jq
          pip3 --no-cache-dir ostree-push yq

      - name: Checkout
        uses: actions/checkout@v3

      - name: OSTree Cache
        uses: actions/cache@v3
        with:
          path: |
            cache/
          key: ${{ runner.os }}-${{ matrix.os }}-ostree

      - name: Build OSTree
        id: build
        run: just ostree_cache=/var/cache/compose ostree_repo=ostree build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ostree
          path: ostree/

  deploy:
    runs-on: ubuntu-latest
    # need artifacts from build job
    needs: build
    container:
      image: ghcr.io/terrapkg/builder:main


    # use matrix for each arch
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        id: deps
        run: pip install ostree-push
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ostree

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
          echo "${{ secrets.GPG_KEY }}" | gpg --import

      - name: Sign OSTree commit
        run: |
          ostree --repo=ostree gpg-sign ultramarine/37/x86_64/lapis ${{ secrets.GPG_ID }} -v
          ostree --repo=ostree summary -u

      - name: Import SSH credentials
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.REPO_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REPO_KNOWN_HOSTS }}

      - name: Push OSTree commit
        run: ostree-push --repo ostree repo@${{ secrets.REPO.IP }}:/var/www/repo.fyralabs.com/ostree
      # - name: Upload OSTree commit to subatomic
      #   run: |
      #     subatomic-cli upload \
      #       --server https://subatomic.fyralabs.com \
      #       --token ${{ secrets.SUBATOMIC_TOKEN }} \
      #       ostree --branch ultramarine/37/x86_64/lapis output.tar || true
