name: Build and deploy OSTree image

on:
  push:
    paths-ignore:
      - "README.md"

  workflow_dispatch:
  schedule:
    # every sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ARM64
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/terrapkg/builder:f38
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: DNF Cache
        uses: actions/cache@v3
        if: always()
        with:
          path: /var/cache/dnf
          key: dnf
      - name: Install dependencies
        id: deps
        run: |
          sudo dnf install -y podman moby-engine rpm-ostree melody just python3-pip pkg-config wget ostree ostree-devel rpm-ostree git hfsplus-tools flatpak dbus dbus-daemon rpmdevtools make mock selinux-policy python3-pip jq @development-tools gcc cairo-devel python3-devel 'pkgconfig(gobject-introspection-1.0)' 'pkgconfig(cairo-gobject)' 'dnf-command(config-manager)'

      - name: Install python dependencies
        id: deps-py
        run: pip install ostree-push yq

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker
        if: always()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up OCI login credentials
      # generate containers-auth.json with podman login --authfile containers-auth.json
      - name: Set up OCI login credentials
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /etc/ostree/auth.json

      - name: Build OSTree
        id: build
        run: just build

      # We are going to build OSTree images through OCI now

      # - name: Import GPG key
      #   run: |
      #     echo "${{ secrets.GPG_SIGNING_KEY }}" | gpg --import
      #     echo "${{ secrets.GPG_KEY }}" | gpg --import

      # - name: Sign OSTree commit
      #   run: |
      #     ostree --repo=/var/ostree gpg-sign ultramarine/37/x86_64/lapis ${{ secrets.GPG_ID }} -v
      #     ostree --repo=/var/ostree summary -u

      # - name: Import SSH credentials
      #   uses: shimataro/ssh-key-action@v2.3.1
      #   with:
      #     key: ${{ secrets.REPO_PRIVATE_KEY }}
      #     known_hosts: ${{ secrets.REPO_KNOWN_HOSTS }}

      # - name: Push OSTree commit
      #   run: ostree-push --repo=/var/ostree repo@${{ secrets.REPO_IP }}:/var/www/repo.fyralabs.com/ostree
